### ISSUE TITLE
Main panicked at 'Could not get start time', src\main.rs:123:18

### ISSUE THREAD

**Issue by Yi-Jiahe** [Yi-Jiahe/hololive-schedule-cli#1]
```
thread 'main' panicked at 'Could not get start time', src\main.rs:123:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Unknown version. Main from [043e674](https://github.com/Yi-Jiahe/hololive-schedule-cli/commit/043e674e3d5fee6d5bc51fbed85cc710a92d3e2d) panic line number does not match.

```
let start: DateTime<Local> = DateTime::from(match stream.live_info {
      VideoLiveInfo {
          start_scheduled: _,
          start_actual: Some(start_actual),
          ..
      } => start_actual,
      VideoLiveInfo {
          start_scheduled: Some(start_scheduled),
          start_actual: None,
          ..
      } => start_scheduled,
      _ => panic!("Could not get start time"),
  });
```

Possibly unhandled case.
Instead of panic-ing and terminating program, it would be better to display an error for the one stream and continue.

**Comment by Yi-Jiahe** [comment]
Fixed in 0d29953 by introducing fallback required field, available_at
